export const FETCH_GENDER_MASTERDATA = 'FETCH_GENDER_MASTERDATA';
export const FETCH_GENDER_MASTERDATA_SUCCESS = 'FETCH_GENDER_MASTERDATA_SUCCESS';
export const FETCH_GENDER_MASTERDATA_FAILURE = 'FETCH_GENDER_MASTERDATA_FAILURE';
