export const FETCH_POKEMON_LIST = 'FETCH_POKEMON_LIST';
export const FETCH_POKEMON_LIST_SUCCESS = 'FETCH_POKEMON_LIST_Success';
export const FETCH_POKEMON_LIST_FAILURE = 'FETCH_POKEMON_LIST_Failure';
export const SEARCH_POKEMON_LIST="SEARCH_POKEMON_LIST";
export const UPDATE_POKEMON_LIST="UPDATE_POKEMON_LIST";