export const FETCH_POKEMON_DETAILS = 'FETCH_POKEMON_DETAILS';
export const FETCH_POKEMON_DETAILS_SUCCESS = 'FETCH_POKEMON_DETAILS_Success';
export const FETCH_POKEMON_DETAILS_FAILURE = 'FETCH_POKEMON_DETAILS_FAILURE';
export const CLEAR_POCKEMON_DETAILS = 'CLEAR_POCKEMON_DETAILS';
export const FETCH_POKEMON_DESCRIPTION = 'FETCH_POKEMON_DESCRIPTION';
export const FETCH_POKEMON_DESCRIPTION_SUCCESS = 'FETCH_POKEMON_DESCRIPTION_SUCCESS';
export const FETCH_POKEMON_DESCRIPTION_FAILURE = 'FETCH_POKEMON_DESCRIPTION_FAILURE';
