export const FETCH_TYPES_MASTERDATA = 'FETCH_TYPES_MASTERDATA';
export const FETCH_TYPES_MASTERDATA_SUCCESS = 'FETCH_TYPES_MASTERDATA_Success';
export const FETCH_TYPES_MASTERDATA_FAILURE = 'FETCH_TYPES_MASTERDATA_Failure';
